# SPDX-License-Identifier: GPL-3.0-or-later

from .lan import (
    CombinedDHCPResponse,
    DHCPSettings,
    DNSSettings,
    LANAddress,
    LANAddressResponse,
    LANNamespace,
)
from .mobile import (
    AvailableNetworkModes,
    CellInfo,
    CellularBasicInfo,
    CurrentWANInfo,
    MobileNamespace,
    NetworkSettings,
    NetworkSettingsResponse,
    SignalInfo,
    WANContext,
)
from .version import MagicNumberInfo, VersionInfo, VersionNamespace
from .wifi import (
    APSection,
    ExtenderConfig,
    ExtenderStatus,
    WiFiAPConfig,
    WiFiAPConfigResponse,
    WiFiBasicInfo,
    WiFiDiagnostics,
    WiFiNamespace,
    WiFiTimedOffStatus,
    WiFiWPSResponse,
    WiFiWPSState,
    WPSStatus,
)

__all__ = [
    "APSection",
    "AvailableNetworkModes",
    "CellInfo",
    "CellularBasicInfo",
    "CombinedDHCPResponse",
    "CurrentWANInfo",
    "DHCPSettings",
    "DNSSettings",
    "ExtenderConfig",
    "ExtenderStatus",
    "LANAddress",
    "LANAddressResponse",
    "LANNamespace",
    "MagicNumberInfo",
    "MobileNamespace",
    "NetworkSettings",
    "NetworkSettingsResponse",
    "SignalInfo",
    "VersionInfo",
    "VersionNamespace",
    "WANContext",
    "WiFiAPConfig",
    "WiFiAPConfigResponse",
    "WiFiBasicInfo",
    "WiFiDiagnostics",
    "WiFiNamespace",
    "WiFiTimedOffStatus",
    "WiFiWPSResponse",
    "WiFiWPSState",
    "WPSStatus",
]
